# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jennifer Hiew
email: jenhiew21@gmail.com
description: The Jekyll version of the Phantom theme by HTML5 UP.
baseurl: "/phantom-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Logo settings
logo-image-url: images/favicon_2017.svg
font-awesome-icon-logo:

# Social settings
etsy_username: Virize
facebook_URL: VirizeArt
github_username: virize
instagram_username: virizeze
linkedin_username: jenniferhiew
tumblr_username: virize
twitter_username: virizeze
phone:

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes
